name: Dependency Review

permissions:
  contents: read

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  merge_group:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Dependency Review
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          fail-on-severity: critical
          fail-on-scopes: development, runtime
          comment-summary-in-pr: on-failure
