name: Dependency Review

permissions:
  contents: read

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  merge_group:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Dependency Review
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4.9.0
        with:
          fail-on-severity: critical
          fail-on-scopes: development, runtime
          comment-summary-in-pr: on-failure
